### ISSUE TITLE
performance and memory

### ISSUE THREAD

**Issue by eduarddrenth** [schxslt/schxslt-java#49]
The Schematron#createValidator method synchronizes on the whole object which may be expensive, scope of synchronization should be as small as possible, in this case you could synchronize on tf in the method around "if templates null". Performance gain may be small.

More important: the schematronvalidator is threadsafe, still you create a new instance of it with every call to validate, this may has a memory effect and impact on the gc. You should avoid creating unnecessary objects, schematronvalidator can be cached in schematron (instead of templates)

**Comment by dmj** [comment]
I think I neet to sychronize on the whole object or at least on both, transformerFactory and validatesTemplates. Both are shared between threads.

Re caching the SchematronValidator: One prerequisite is to remove the public setPipelineSteps() method. Otherwise I would have to nullify SchematronValidator.

**Comment by eduarddrenth** [comment]
I'll have a look....

**Comment by eduarddrenth** [comment]
setPipelineSteps is only called from deprecated with...method

**Comment by eduarddrenth** [comment]
is it ok with you if in my pr I remove the with* methods? Than a lot can be optimized

**Comment by dmj** [comment]
Yes, I merged the PR (thanks!). I also released v2.0.4 aus the last release of the 2.x series and bumped the version to 3.0-SNAPSHOT.
